# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    main:
        name: Android PhoneLib Main
        max_build_duration: 30
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: false
        scripts:
            - name: Build library file
              script: ./gradlew clean build
        artifacts:
            - app/build/outputs/**/*.aar