workflows:
  android-workflow:
    name: Build Android VoIP Lib
    max_build_duration: 60
    instance_type: mac_pro
    environment:
      node: latest
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Build for Android (.apk)
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk